name: Construir aplicación para Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: pip

      - name: Construir el ejecutable
        shell: pwsh
        run: ./build_windows.ps1

      - name: Publicar el ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: Programador-de-alarmas-Windows
          path: dist/windows/Programador-de-alarmas.exe
          if-no-files-found: error
